### ISSUE TITLE
Awessome Books Issues

### ISSUE THREAD

**Issue by carreraprogrammer** [carreraprogrammer/Awessome-books#3]
**This space is to comment on the Issues of the project Awesome Books**

**Comment by Camilovelag** [comment]
# Good day, @carreraprogrammer! 🌤️

Your app looks pretty good, but in order to improve it, I would like to suggest the following changes:

![done](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

## 🛠️ Changes to do

- [x]  Use the CSS `tr:nth-child(even)` and `tr:nth-child(odd)` rules to style the Booklist section instead using `index.js`. For more info, visit https://www.w3.org/Style/Examples/007/evenodd.en.html

### Optional suggestions

_No optional changes/suggestions to add._

Happy coding!👏👏👏
